binop_separator = "Back"
blank_lines_upper_bound = 0
fn_single_line = true
format_code_in_doc_comments = true
newline_style = "Unix"
normalize_comments = true
tab_spaces = 2
trailing_comma = "Never"
unstable_features = true
use_try_shorthand = true
wrap_comments = true